name: publish extension
on:
  push:
    branches:
      - main
  release:
      types:
      - created
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install the dependencies
      run: npm i

    - name: Install vsce
      run: npm i -g vsce
    # - run: xvfb-run -a npm test
    #   if: runner.os == 'Linux'
    # - run: npm test
    #   if: runner.os != 'Linux'
    - name: compile and create vsix
      run: vsce package
    - name: upload vsix as artifact
      uses: actions/upload-artifact@v3
      with:
        path: ${{github.workspace}}/vscode-sailpoint-identitynow-*.vsix
    - name: Publish
      if: success() && startsWith( github.ref, 'refs/tags/releases/')
      run: vsce publish -p ${{ secrets.VSCE_PAT }}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: success() && startsWith( github.ref, 'refs/tags/releases/')
      with:
        files: vscode-sailpoint-identitynow-*.vsix